[2022-06-17 18:54:46,873] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: coffee_lake_scrapers-v1.upload_imgs manual__2022-06-17T18:54:14.324395+00:00 [queued]>
[2022-06-17 18:54:46,884] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: coffee_lake_scrapers-v1.upload_imgs manual__2022-06-17T18:54:14.324395+00:00 [queued]>
[2022-06-17 18:54:46,885] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 18:54:46,885] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-17 18:54:46,885] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 18:54:46,900] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): upload_imgs> on 2022-06-17 18:54:14.324395+00:00
[2022-06-17 18:54:46,904] {standard_task_runner.py:52} INFO - Started process 906 to run task
[2022-06-17 18:54:46,907] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'coffee_lake_scrapers-v1', 'upload_imgs', 'manual__2022-06-17T18:54:14.324395+00:00', '--job-id', '263', '--raw', '--subdir', 'DAGS_FOLDER/scraper_dag.py', '--cfg-path', '/tmp/tmpi3m594t0', '--error-file', '/tmp/tmpv77cgvm3']
[2022-06-17 18:54:46,907] {standard_task_runner.py:80} INFO - Job 263: Subtask upload_imgs
[2022-06-17 18:54:46,956] {task_command.py:370} INFO - Running <TaskInstance: coffee_lake_scrapers-v1.upload_imgs manual__2022-06-17T18:54:14.324395+00:00 [running]> on host c0a717b7b476
[2022-06-17 18:54:47,025] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=coffee_lake_scrapers-v1
AIRFLOW_CTX_TASK_ID=upload_imgs
AIRFLOW_CTX_EXECUTION_DATE=2022-06-17T18:54:14.324395+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-17T18:54:14.324395+00:00
[2022-06-17 18:54:47,035] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scraper_dag.py", line 161, in upload_imgs
    upload_img_to_gcs(img=img, uploaded_filename=outfile)
  File "/opt/airflow/dags/scraper_dag.py", line 190, in upload_img_to_gcs
    decoded_img = pybase64.b64encode(img)
TypeError: a bytes-like object is required, not 'PngImageFile'
[2022-06-17 18:54:47,051] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=coffee_lake_scrapers-v1, task_id=upload_imgs, execution_date=20220617T185414, start_date=20220617T185446, end_date=20220617T185447
[2022-06-17 18:54:47,063] {standard_task_runner.py:97} ERROR - Failed to execute job 263 for task upload_imgs (a bytes-like object is required, not 'PngImageFile'; 906)
[2022-06-17 18:54:47,080] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-17 18:54:47,116] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
